apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: content-mgnt-service
  namespace: dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/my-apps/app-1
    repoURL: https://github.com/mvalikar/argo-cd-example.git
    targetRevision: HEAD